### PR TITLE
add LUT6_2 support

### PR DESCRIPTION
**Pull request by lehaifeng000**

### CODE REVIEW

**Comment by hansfbaier** [comment]
Thanks @lehaifeng000 for that contribution.
I already manually merged commit 01e68370d2e005820420fb1f1b9868861af2358c,
I also updated the nextpnr-xilinx-meta project and submodule to
use the repository from openXC7 instead of gatecat.
So that part is different from your PR.
I will close this PR accordingly.
Please do a git pull to update.

**Comment by hansfbaier** [comment]
@lehaifeng000 I hope I did not discourage you by closing this PR.
I actually merged your change, because I had to cherry pick the first commit.
I only could not merge this part, because it needs to point to the openXC7 repository:
image

**Comment by hansfbaier** [comment]
@lehaifeng000 Keep on the good work, and I am glad for your contributions. Feel free to ask whenever you have questions, I am ready to help!

**Comment by lehaifeng000** [comment]
yes, i am glad to see that, it really dosenot matter ~
Now i am reading the nextpnr code and tring to find a good solution

**Pull request closed without merging**
